### ISSUE TITLE
Build failed (configure.sh: invalid option '-fPIC')

### ISSUE THREAD

**Issue by tkclimb** [cowanmeg/cgo-artifact-2020#3]
hi
I read this preprint. it's awesome paper! thanks for opening the source code.
anyway, when I tired to setup this project in my docker environment, it failed with the following error.

```shell
> docker build -t cgo-art cgo-artifact-2020/docker
...
Step 13/20 : RUN ./contrib/setup-btor2tools.sh
 ---> Running in fab94060d35f
Cloning into '/boolector/deps/btor2tools'...
*** configure.sh: invalid option '-fPIC' (try '-h')
```

it seems bootlector has some problem on its build scripts.
I just tried to fix above by adding the following lines in Dockerfile.
```
# add curl to install
RUN apt-get update && apt-get install -y \
  ...
  curl
# change the commit id into current master (it uses curl inside)
RUN git checkout 30132cb434a4ec2ed2389eb904fde97ae09292f8
```

this workaround solved the above issue but i'm not sure the version of boolector is proper or not, so i didn't create pull request.

**Comment by cowanmeg** [comment]
Thanks for finding this!
